BOX_IMAGE  = "generic/alpine312"
NODE_NAME  = "machine"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  
  (0..(NODE_COUNT - 1)).each do |_sx1|
    config.vm.define "#{NODE_NAME}#{_sx1}" do |subconfig|
      subconfig.vm.box       = BOX_IMAGE
      subconfig.vm.provision :shell, path: "bootstrap.sh"
      subconfig.vm.hostname  = "#{NODE_NAME}#{_sx1}"
      subconfig.vm.network   "public_network", type: "dhcp", bridge: "enp4s0"
      subconfig.vm.disk      :disk, name: "#{NODE_NAME}#{_sx1}-dsk-a", size: "2GB"
      subconfig.vm.provider  "virtualbox" do |vbox|
        vbox.memory = 2048
        vbox.cpus   = 2
      end
    end
  end

end
