
Vagrant.configure("2") do |config|

  config.vm.define "tq01", primary: true do |ta01|
    config.vm.box = "hashicorp/bionic64"
    config.vm.provision :shell, path: "bootstrap.sh"
  
  # config.vm.network "private_network", :forwarded_port, guest: 80, host: 4567
    config.vm.network "public_network",  type: "dhcp", bridge: "enp4s0"  
  end

  config.vm.define "tq02" do |tq02|
    config.vm.box = "hashicorp/bionic64"
    config.vm.provision :shell, path: "bootstrap.sh"
  
  # config.vm.network "private_network", :forwarded_port, guest: 80, host: 4567
    config.vm.network "public_network",  type: "dhcp", bridge: "enp4s0"  
  end
end
